- project:
    templates:
      - openstack-python3-victoria-jobs
      - check-requirements
    check:
      jobs:
        - ec2api-tempest-plugin-functional
        - ec2api-tempest-plugin-functional-xena
        - ec2api-tempest-plugin-functional-wallaby
        - ec2api-tempest-plugin-functional-victoria
        - ec2api-tempest-plugin-functional-ussuri
    gate:
      queue: ec2-api
      jobs:
        - ec2api-tempest-plugin-functional
    experimental:
      jobs:
        - ec2api-tempest-plugin-functional-full

- job:
    name: ec2api-tempest-plugin-functional
    parent: devstack-tempest
    timeout: 7800
    required-projects:
      - opendev.org/openstack/ec2-api
      - opendev.org/openstack/ec2api-tempest-plugin
      - opendev.org/openstack/neutron
      - opendev.org/openstack/neutron-vpnaas
      - opendev.org/openstack/neutron-tempest-plugin
    vars:
      devstack_localrc:
        KEYSTONE_ADMIN_ENDPOINT: true
      devstack_services:
        tls-proxy: false
      tox_envlist: all
      tempest_test_regex: ec2api_tempest_plugin
      tempest_concurrency: 2
      devstack_plugins:
        ec2-api: https://opendev.org/openstack/ec2-api
        neutron-tempest-plugin: https://opendev.org/openstack/neutron-tempest-plugin
      tempest_plugins:
        - ec2api-tempest-plugin

- job:
    name: ec2api-tempest-plugin-functional-xena
    parent: ec2api-tempest-plugin-functional
    override-checkout: stable/xena

- job:
    name: ec2api-tempest-plugin-functional-wallaby
    parent: ec2api-tempest-plugin-functional
    override-checkout: stable/wallaby

- job:
    name: ec2api-tempest-plugin-functional-victoria
    parent: ec2api-tempest-plugin-functional
    override-checkout: stable/victoria

- job:
    name: ec2api-tempest-plugin-functional-ussuri
    parent: ec2api-tempest-plugin-functional
    override-checkout: stable/ussuri

- job:
    name: ec2api-tempest-plugin-functional-full
    parent: ec2api-tempest-plugin-functional
    vars:
      devstack_localrc:
        RUN_LONG_TESTS: 1
